---
#RedHat specific tasks

- name: "Ensure Treasure Data repository exists"
  yum_repository:
    name: treasuredata
    description: "Treasure Data Repository"
    baseurl: "http://packages.treasuredata.com/2/redhat/$releasever/$basearch"
    gpgkey: "https://packages.treasuredata.com/GPG-KEY-td-agent"
    gpgcheck: yes
